<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Service;
use App\Models\ServiceCategory;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        // Récupérer les catégories existantes
        $prestationCategory = ServiceCategory::where('slug', 'prestation')->first();
        $logistiqueCategory = ServiceCategory::where('slug', 'logistique')->first();

        // Tous les services disponibles
        $services = [
            // SERVICES DE PRESTATION AGRICOLE
            [
                'name' => 'Défrichage',
                'category_id' => $prestationCategory->id,
                'description' => 'Nettoyage et défrichage des terrains agricoles, préparation des parcelles.',
                'icon' => 'defrichage-icon',
                'image_path' => '/images/services/defrichage.jpg',
                'meta_title' => 'Service de défrichage agricole',
                'meta_description' => 'Défrichage professionnel de terrains agricoles pour préparer vos cultures',
                'meta_keywords' => ['défrichage', 'nettoyage terrain', 'préparation sol'],
                'sort_order' => 1,
            ],
            [
                'name' => 'Labour',
                'category_id' => $prestationCategory->id,
                'description' => 'Labour des champs pour préparer le sol avant les semis.',
                'icon' => 'labour-icon',
                'image_path' => '/images/services/labour.jpg',
                'meta_title' => 'Service de labour agricole',
                'meta_description' => 'Labour professionnel des champs avec équipement adapté',
                'meta_keywords' => ['labour', 'préparation sol', 'travail du sol'],
                'sort_order' => 2,
            ],
            [
                'name' => 'Buttage',
                'category_id' => $prestationCategory->id,
                'description' => 'Buttage des cultures pour favoriser le développement des racines.',
                'icon' => 'buttage-icon',
                'image_path' => '/images/services/buttage.jpg',
                'meta_title' => 'Service de buttage',
                'meta_description' => 'Buttage professionnel pour vos cultures',
                'meta_keywords' => ['buttage', 'culture', 'entretien culture'],
                'sort_order' => 3,
            ],
            [
                'name' => 'Semis',
                'category_id' => $prestationCategory->id,
                'description' => 'Service de semis pour toutes vos cultures agricoles.',
                'icon' => 'semis-icon',
                'image_path' => '/images/services/semis.jpg',
                'meta_title' => 'Service de semis agricole',
                'meta_description' => 'Semis professionnel pour toutes vos cultures',
                'meta_keywords' => ['semis', 'plantation', 'mise en culture'],
                'sort_order' => 4,
            ],
            [
                'name' => 'Application pesticide',
                'category_id' => $prestationCategory->id,
                'description' => 'Application professionnelle de pesticides pour protéger vos cultures.',
                'icon' => 'pesticide-icon',
                'image_path' => '/images/services/pesticide.jpg',
                'meta_title' => 'Application de pesticides',
                'meta_description' => 'Traitement phytosanitaire professionnel pour vos cultures',
                'meta_keywords' => ['pesticide', 'traitement', 'protection cultures'],
                'sort_order' => 5,
            ],
            [
                'name' => 'Épandage d\'engrais',
                'category_id' => $prestationCategory->id,
                'description' => 'Épandage d\'engrais organiques et chimiques pour fertiliser vos sols.',
                'icon' => 'engrais-icon',
                'image_path' => '/images/services/epandage.jpg',
                'meta_title' => 'Service d\'épandage d\'engrais',
                'meta_description' => 'Fertilisation professionnelle de vos parcelles agricoles',
                'meta_keywords' => ['engrais', 'fertilisation', 'épandage'],
                'sort_order' => 6,
            ],
            [
                'name' => 'Transit et dédouanement',
                'category_id' => $prestationCategory->id,
                'description' => 'Services de transit et dédouanement pour l\'import/export de produits agricoles.',
                'icon' => 'transit-icon',
                'image_path' => '/images/services/transit.jpg',
                'meta_title' => 'Transit et dédouanement agricole',
                'meta_description' => 'Services de transit et dédouanement pour produits agricoles',
                'meta_keywords' => ['transit', 'dédouanement', 'douane', 'import export'],
                'sort_order' => 7,
            ],
            [
                'name' => 'Conseil agricole',
                'category_id' => $prestationCategory->id,
                'description' => 'Conseils et expertise agricole pour optimiser vos productions.',
                'icon' => 'conseil-icon',
                'image_path' => '/images/services/conseil.jpg',
                'meta_title' => 'Conseil agricole',
                'meta_description' => 'Expertise et conseils pour améliorer vos rendements agricoles',
                'meta_keywords' => ['conseil', 'expertise', 'agronomie'],
                'sort_order' => 8,
            ],
            [
                'name' => 'Maintenance agricole',
                'category_id' => $prestationCategory->id,
                'description' => 'Maintenance et réparation de matériel agricole.',
                'icon' => 'maintenance-icon',
                'image_path' => '/images/services/maintenance.jpg',
                'meta_title' => 'Maintenance matériel agricole',
                'meta_description' => 'Service de maintenance et réparation de matériel agricole',
                'meta_keywords' => ['maintenance', 'réparation', 'matériel agricole'],
                'sort_order' => 9,
            ],
            [
                'name' => 'Récolte mécanisée',
                'category_id' => $prestationCategory->id,
                'description' => 'Service de récolte mécanisée pour grandes cultures.',
                'icon' => 'recolte-icon',
                'image_path' => '/images/services/recolte.jpg',
                'meta_title' => 'Récolte mécanisée',
                'meta_description' => 'Service professionnel de récolte mécanisée',
                'meta_keywords' => ['récolte', 'moisson', 'mécanisation'],
                'sort_order' => 10,
            ],
            [
                'name' => 'Irrigation',
                'category_id' => $prestationCategory->id,
                'description' => 'Installation et gestion de systèmes d\'irrigation.',
                'icon' => 'irrigation-icon',
                'image_path' => '/images/services/irrigation.jpg',
                'meta_title' => 'Service d\'irrigation agricole',
                'meta_description' => 'Installation et gestion de systèmes d\'irrigation',
                'meta_keywords' => ['irrigation', 'arrosage', 'eau'],
                'sort_order' => 11,
            ],
            [
                'name' => 'Traitement post-récolte',
                'category_id' => $prestationCategory->id,
                'description' => 'Services après récolte : séchage, tri, conditionnement.',
                'icon' => 'postrecolte-icon',
                'image_path' => '/images/services/postrecolte.jpg',
                'meta_title' => 'Traitement post-récolte',
                'meta_description' => 'Services de traitement et conditionnement après récolte',
                'meta_keywords' => ['post-récolte', 'séchage', 'conditionnement'],
                'sort_order' => 12,
            ],

            // SERVICES LOGISTIQUES (Transporteur)
            [
                'name' => 'Transport urbain',
                'category_id' => $logistiqueCategory->id,
                'description' => 'Transport de produits agricoles en zone urbaine et périurbaine.',
                'icon' => 'transport-urbain-icon',
                'image_path' => '/images/services/transport-urbain.jpg',
                'meta_title' => 'Transport urbain de produits agricoles',
                'meta_description' => 'Service de transport urbain pour produits agricoles',
                'meta_keywords' => ['transport urbain', 'livraison ville', 'coursier'],
                'sort_order' => 1,
            ],
            [
                'name' => 'Transport national',
                'category_id' => $logistiqueCategory->id,
                'description' => 'Transport de produits agricoles à l\'échelle nationale.',
                'icon' => 'transport-national-icon',
                'image_path' => '/images/services/transport-national.jpg',
                'meta_title' => 'Transport national agricole',
                'meta_description' => 'Service de transport national pour produits agricoles',
                'meta_keywords' => ['transport national', 'camionnage', 'fret'],
                'sort_order' => 2,
            ],
            [
                'name' => 'Transport sous-régional',
                'category_id' => $logistiqueCategory->id,
                'description' => 'Transport de produits agricoles dans l\'espace sous-régional (CEDEAO, etc.).',
                'icon' => 'transport-regional-icon',
                'image_path' => '/images/services/transport-regional.jpg',
                'meta_title' => 'Transport sous-régional agricole',
                'meta_description' => 'Service de transport sous-régional pour produits agricoles',
                'meta_keywords' => ['transport régional', 'CEDEAO', 'transfrontalier'],
                'sort_order' => 3,
            ],
            [
                'name' => 'Transport international',
                'category_id' => $logistiqueCategory->id,
                'description' => 'Transport de produits agricoles à l\'international.',
                'icon' => 'transport-international-icon',
                'image_path' => '/images/services/transport-international.jpg',
                'meta_title' => 'Transport international agricole',
                'meta_description' => 'Service de transport international pour produits agricoles',
                'meta_keywords' => ['transport international', 'export', 'import', 'fret'],
                'sort_order' => 4,
            ],
            [
                'name' => 'Livraison par moto',
                'category_id' => $logistiqueCategory->id,
                'description' => 'Livraison rapide de petits volumes par moto.',
                'icon' => 'moto-icon',
                'image_path' => '/images/services/moto.jpg',
                'meta_title' => 'Livraison par moto',
                'meta_description' => 'Service de livraison rapide par moto pour petits volumes',
                'meta_keywords' => ['moto', 'livraison rapide', 'coursier'],
                'sort_order' => 5,
            ],
            [
                'name' => 'Livraison par tricycle',
                'category_id' => $logistiqueCategory->id,
                'description' => 'Transport de marchandises par tricycle pour livraisons locales.',
                'icon' => 'tricycle-icon',
                'image_path' => '/images/services/tricycle.jpg',
                'meta_title' => 'Livraison par tricycle',
                'meta_description' => 'Service de transport local par tricycle',
                'meta_keywords' => ['tricycle', 'livraison locale', 'marchandises'],
                'sort_order' => 6,
            ],
            [
                'name' => 'Transport par camion',
                'category_id' => $logistiqueCategory->id,
                'description' => 'Transport de gros volumes par camion pour longues distances.',
                'icon' => 'camion-icon',
                'image_path' => '/images/services/camion.jpg',
                'meta_title' => 'Transport par camion',
                'meta_description' => 'Service de transport de gros volumes par camion',
                'meta_keywords' => ['camion', 'poids lourd', 'transport vrac'],
                'sort_order' => 7,
            ],
            [
                'name' => 'Transport par titan',
                'category_id' => $logistiqueCategory->id,
                'description' => 'Transport de très gros volumes par titan (super poids lourd).',
                'icon' => 'titan-icon',
                'image_path' => '/images/services/titan.jpg',
                'meta_title' => 'Transport par titan',
                'meta_description' => 'Service de transport de très gros volumes par titan',
                'meta_keywords' => ['titan', 'super poids lourd', 'convoi exceptionnel'],
                'sort_order' => 8,
            ],
            [
                'name' => 'Transport par bateau',
                'category_id' => $logistiqueCategory->id,
                'description' => 'Transport fluvial ou maritime de produits agricoles.',
                'icon' => 'bateau-icon',
                'image_path' => '/images/services/bateau.jpg',
                'meta_title' => 'Transport par bateau',
                'meta_description' => 'Service de transport fluvial et maritime pour produits agricoles',
                'meta_keywords' => ['bateau', 'maritime', 'fluvial', 'transport eau'],
                'sort_order' => 9,
            ],
            [
                'name' => 'Transport par avion',
                'category_id' => $logistiqueCategory->id,
                'description' => 'Transport aérien pour produits agricoles périssables ou urgents.',
                'icon' => 'avion-icon',
                'image_path' => '/images/services/avion.jpg',
                'meta_title' => 'Transport par avion',
                'meta_description' => 'Service de transport aérien pour produits agricoles',
                'meta_keywords' => ['avion', 'aérien', 'fret aérien', 'urgent'],
                'sort_order' => 10,
            ],
            [
                'name' => 'Entreposage et stockage',
                'category_id' => $logistiqueCategory->id,
                'description' => 'Services d\'entreposage et stockage de produits agricoles.',
                'icon' => 'stockage-icon',
                'image_path' => '/images/services/stockage.jpg',
                'meta_title' => 'Entreposage agricole',
                'meta_description' => 'Service d\'entreposage et stockage de produits agricoles',
                'meta_keywords' => ['stockage', 'entreposage', 'entrepôt', 'magasin'],
                'sort_order' => 11,
            ],
            [
                'name' => 'Logistique du froid',
                'category_id' => $logistiqueCategory->id,
                'description' => 'Transport et stockage de produits agricoles sous température contrôlée.',
                'icon' => 'froid-icon',
                'image_path' => '/images/services/froid.jpg',
                'meta_title' => 'Logistique du froid',
                'meta_description' => 'Service de transport et stockage de produits périssables sous température contrôlée',
                'meta_keywords' => ['froid', 'chaîne du froid', 'réfrigéré', 'congelé'],
                'sort_order' => 12,
            ],
            [
                'name' => 'Location de véhicules',
                'category_id' => $logistiqueCategory->id,
                'description' => 'Location de véhicules pour transport agricole avec ou sans chauffeur.',
                'icon' => 'location-icon',
                'image_path' => '/images/services/location.jpg',
                'meta_title' => 'Location de véhicules agricoles',
                'meta_description' => 'Service de location de véhicules pour transport agricole',
                'meta_keywords' => ['location', 'véhicule', 'camion location'],
                'sort_order' => 13,
            ],
        ];

        foreach ($services as $service) {
            Service::updateOrCreate(
                ['slug' => Str::slug($service['name'])],
                [
                    'service_category_id' => $service['category_id'],
                    'name' => $service['name'],
                    'slug' => Str::slug($service['name']),
                    'description' => $service['description'],
                    'icon' => $service['icon'],
                    'image_path' => $service['image_path'],
                    'meta_title' => $service['meta_title'],
                    'meta_description' => $service['meta_description'],
                    'meta_keywords' => $service['meta_keywords'],
                    'is_active' => true,
                    'sort_order' => $service['sort_order'],
                ]
            );
        }
    }
}
